def set_handSelected(hand):
    global _handSelected
    _handSelected = hand

RIGHT_HAND = 0
LEFT_HAND = 1

# 默认右手
_handSelected = RIGHT_HAND 

# 机械臂运动相关参数
TABLE_HEIGHT = 0.72
BASE_HEIGHT = 0.80

OBJECT_DISTANCE = 0.56
HOLE_DISTANCE = 0.1775

OFFSET_BASE_TABLE = TABLE_HEIGHT - BASE_HEIGHT

POS_LEFT = 0
POS_MIDDLE = 1
POS_RIGHT = 2

#
# 球相关参数
BALL_HEIGHT = [0.281, 0.231]  # [拿住球高度, 去拿球高度]
BALL_DISTANCE = [-0.084, -0.226, -0.084]  # [去拿球, 拿住球回缩, 拿住球移动]
BALL_HAND = [
    [0.016, 0.016],   # 右手 [拿住球距离, 抓起球距离]
    [-0.024, -0.024]  # 左手 [拿住球距离, 抓起球距离]
]
BALL_ANGLE_LIFT = [2.382, -0.832, 2.361]
BALL_ANGLE_LIFT_BACK = [1.568, -1.07, 3.042]
BALL_ANGLE_GRASP = [2.382, -0.832, 2.361]

#
# 瓶相关参数
BOTTLE_HEIGHT = [0.231, 0.181]  # [拿住瓶高度, 去拿瓶高度]
BOTTLE_DISTANCE = [-0.112, -0.256, -0.112]  # [去拿瓶, 拿住瓶回缩, 拿住瓶移动]
BOTTLE_HAND = [
    [0.037, 0.037, 0.037],    # 右手 [拿住瓶距离, 抓起瓶距离, 抓起瓶回缩距离]
    [-0.037, -0.037, -0.037]  # 左手 [拿住瓶距离, 抓起瓶距离, 抓起瓶回缩距离]
]
BOTTLE_ANGLE_RIGHT = [
    # rx,   ry,    rz
    [-1.573, -0.573, -0.155],  # Lift
    [-1.573, -0.573, -0.155],  # LiftBack
    [-1.573, -0.573, -0.055]   # Grasp
]
BOTTLE_ANGLE_LEFT = [
    # rx,   ry,    rz
    [1.573, 0.474, 3.149],     # Lift
    [1.573, 0.474, -3.034],    # LiftBack
    [1.573, 0.474, 3.149]      # Grasp
]

MAX_SINGLE_FINGER_POS = [65535]
MIN_SINGLE_FINGER_POS = [0]

HAND_FIST_CLOSE_POS = [0, 65535, 65535, 65535, 65535, 65535]
HAND_FIST_OPEN_POS = [0, 0, 0, 0, 0, 65535]
HAND_VICTORY_POS = [65535, 0, 0, 65535, 65535, 65535]

HAND_READY_GRASP_BALL_POS = [0, 0, 0, 0, 0, 50535]
HAND_GRASP_BALL_POS = [9000, 18000, 20000, 0, 0, 50535]

HAND_READY_GRASP_BOTTLE_POS = [0, 0, 0, 0, 0, 65535]
HAND_GRASP_BOTTLE_POS = [15000, 30000, 26000, 24000, 20000, 65535]
HAND_INITIAL_POS = [0, 0, 0, 0, 0, 0]

#
# 球相关姿态
POSE_LIFT_LEFT_BALL_BACK_HIGH = [
    [BALL_HAND[0][0] - HOLE_DISTANCE, BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK],
    [BALL_HAND[1][0] - HOLE_DISTANCE, BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK]
]
POSE_LIFT_MIDDLE_BALL_BACK_HIGH = [
    [BALL_HAND[0][0], BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK],
    [BALL_HAND[1][0], BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK]
]
POSE_LIFT_RIGHT_BALL_BACK_HIGH = [
    [BALL_HAND[0][0] + HOLE_DISTANCE, BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK],
    [BALL_HAND[1][0] + HOLE_DISTANCE, BALL_DISTANCE[1] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT_BACK]
]
POSE_LIFT_BALL_BACK_HIGH = [
    POSE_LIFT_LEFT_BALL_BACK_HIGH[_handSelected],
    POSE_LIFT_MIDDLE_BALL_BACK_HIGH[_handSelected],
    POSE_LIFT_RIGHT_BALL_BACK_HIGH[_handSelected]
]

POSE_GRASP_LEFT_BALL = [
    [BALL_HAND[0][1] - HOLE_DISTANCE, BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP],
    [BALL_HAND[1][1] - HOLE_DISTANCE, BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP]
]
POSE_GRASP_MIDDLE_BALL = [
    [BALL_HAND[0][1], BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP],
    [BALL_HAND[1][1], BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP]
]
POSE_GRASP_RIGHT_BALL = [
    [BALL_HAND[0][1] + HOLE_DISTANCE, BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP],
    [BALL_HAND[1][1] + HOLE_DISTANCE, BALL_DISTANCE[2] + OBJECT_DISTANCE, BALL_HEIGHT[1] + OFFSET_BASE_TABLE, *BALL_ANGLE_GRASP]
]
POSE_GRASP_BALL = [
    POSE_GRASP_LEFT_BALL[_handSelected],
    POSE_GRASP_MIDDLE_BALL[_handSelected],
    POSE_GRASP_RIGHT_BALL[_handSelected]
]

POSE_LIFT_LEFT_BALL_HIGH = [
    [BALL_HAND[0][0] - HOLE_DISTANCE, BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT],
    [BALL_HAND[1][0] - HOLE_DISTANCE, BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT]
]
POSE_LIFT_MIDDLE_BALL_HIGH = [
    [BALL_HAND[0][0], BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT],
    [BALL_HAND[1][0], BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT]
]
POSE_LIFT_RIGHT_BALL_HIGH = [
    [BALL_HAND[0][0] + HOLE_DISTANCE, BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT],
    [BALL_HAND[1][0] + HOLE_DISTANCE, BALL_DISTANCE[0] + OBJECT_DISTANCE, BALL_HEIGHT[0] + OFFSET_BASE_TABLE, *BALL_ANGLE_LIFT]
]
POSE_LIFT_BALL_HIGH = [
    POSE_LIFT_LEFT_BALL_HIGH[_handSelected],
    POSE_LIFT_MIDDLE_BALL_HIGH[_handSelected],
    POSE_LIFT_RIGHT_BALL_HIGH[_handSelected]
]

#
# 瓶相关姿态
POSE_LIFT_LEFT_BOTTLE_BACK_HIGH = [
    [BOTTLE_HAND[0][2] - HOLE_DISTANCE, BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[1]],
    [BOTTLE_HAND[1][2] - HOLE_DISTANCE, BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[1]]
]
POSE_LIFT_MIDDLE_BOTTLE_BACK_HIGH = [
    [BOTTLE_HAND[0][2], BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[1]],
    [BOTTLE_HAND[1][2], BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[1]]
]
POSE_LIFT_RIGHT_BOTTLE_BACK_HIGH = [
    [BOTTLE_HAND[0][2] + HOLE_DISTANCE, BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[1]],
    [BOTTLE_HAND[1][2] + HOLE_DISTANCE, BOTTLE_DISTANCE[1] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[1]]
]
POSE_LIFT_BOTTLE_BACK_HIGH = [
    POSE_LIFT_LEFT_BOTTLE_BACK_HIGH[_handSelected],
    POSE_LIFT_MIDDLE_BOTTLE_BACK_HIGH[_handSelected],
    POSE_LIFT_RIGHT_BOTTLE_BACK_HIGH[_handSelected]
]

POSE_GRASP_LEFT_BOTTLE = [
    [BOTTLE_HAND[0][1] - HOLE_DISTANCE, BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, BOTTLE_ANGLE_RIGHT[2][0] + 0.007, BOTTLE_ANGLE_RIGHT[2][1], BOTTLE_ANGLE_RIGHT[2][2]],
    [BOTTLE_HAND[1][1] - HOLE_DISTANCE, BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[2]]
]
POSE_GRASP_MIDDLE_BOTTLE = [
    [BOTTLE_HAND[0][1], BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[2]],
    [BOTTLE_HAND[1][1], BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[2]]
]
POSE_GRASP_RIGHT_BOTTLE = [
    [BOTTLE_HAND[0][1] + HOLE_DISTANCE, BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[2]],
    [BOTTLE_HAND[1][1] + HOLE_DISTANCE, BOTTLE_DISTANCE[2] + OBJECT_DISTANCE, BOTTLE_HEIGHT[1] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[2]]
]
POSE_GRASP_BOTTLE = [
    POSE_GRASP_LEFT_BOTTLE[_handSelected],
    POSE_GRASP_MIDDLE_BOTTLE[_handSelected],
    POSE_GRASP_RIGHT_BOTTLE[_handSelected]
]

POSE_LIFT_LEFT_BOTTLE_HIGH = [
    [BOTTLE_HAND[0][0] - HOLE_DISTANCE, BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[0]],
    [BOTTLE_HAND[1][0] - HOLE_DISTANCE, BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[0]]
]
POSE_LIFT_MIDDLE_BOTTLE_HIGH = [
    [BOTTLE_HAND[0][0], BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[0]],
    [BOTTLE_HAND[1][0], BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[0]]
]
POSE_LIFT_RIGHT_BOTTLE_HIGH = [
    [BOTTLE_HAND[0][0] + HOLE_DISTANCE, BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_RIGHT[0]],
    [BOTTLE_HAND[1][0] + HOLE_DISTANCE, BOTTLE_DISTANCE[0] + OBJECT_DISTANCE, BOTTLE_HEIGHT[0] + OFFSET_BASE_TABLE, *BOTTLE_ANGLE_LEFT[0]]
]
POSE_LIFT_BOTTLE_HIGH = [
    POSE_LIFT_LEFT_BOTTLE_HIGH[_handSelected],
    POSE_LIFT_MIDDLE_BOTTLE_HIGH[_handSelected],
    POSE_LIFT_RIGHT_BOTTLE_HIGH[_handSelected]
]

# 其他姿态
POSE_INITIAL = [78.609, 0, 0, 0, 0, 0]
POSE_VICTORY = [
    [78.609, 2.912, -123.641, -2.634, 110.595, -48.045],
    [78.609, 2.912, -123.641, -2.634, 110.595, -18.045],
    [78.609, 2.912, -123.641, -2.634, 110.595, 11.954]
]
POSE_DANCE = [89.638, -59.8, -124.738, 3.685, 111.726, -17.166]
